### ISSUE TITLE
Any plan to export the API Key & Stages Information?

### ISSUE THREAD

**Issue by AlexOugh** [isabinin/aws-apigateway-swagger-exporter#5]
It looks like the api keys and their related information in APIs & API stages are NOT exported. Not sure if the importer tool supports these, but I'm wondering if you have any plan for these.

**Comment by isabinin** [comment]
This tool exports API specification which includes resources and models. The Swagger file it produces can be imported using Amazon's API Gateway Importer (https://github.com/awslabs/aws-apigateway-importer) and it will produce the same API specification.
API stage settings (Cache Settings, CloudWatch Settings, etc.) and API account level settings (API keys, Custom Domain Names, etc.) are not supported. The main reason why is because AWS API Gateway Importer doesn't support these settings in Swagger file.

I can't promise, but maybe I'll implement exporting and importing of these kind of settings. It seems to be useful feature.
